#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AOB426

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// Class AOB426.AOB426GameModeBase
// 0x0000 (0x02C0 - 0x02C0)
class AAOB426GameModeBase final : public AGameModeBase
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"AOB426GameModeBase">();
	}
	static class AAOB426GameModeBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<AAOB426GameModeBase>();
	}
};
static_assert(alignof(AAOB426GameModeBase) == 0x000008, "Wrong alignment on AAOB426GameModeBase");
static_assert(sizeof(AAOB426GameModeBase) == 0x0002C0, "Wrong size on AAOB426GameModeBase");

}

