#include "..\FUObjectArray.hpp"
#include "..\_Script_CoreUObject\Class.hpp"
#include "..\_Script_CoreUObject\Object.hpp"
#include "EdGraphPin_Deprecated.hpp"
void* _Script_Engine::EdGraphPin_Deprecated::get_PinName() {
    return (void*)((uintptr_t)this + 0x28);
}
void* _Script_Engine::EdGraphPin_Deprecated::get_PinToolTip() {
    return (void*)((uintptr_t)this + 0x38);
}
void* _Script_Engine::EdGraphPin_Deprecated::get_AutogeneratedDefaultValue() {
    return (void*)((uintptr_t)this + 0xb8);
}
void* _Script_Engine::EdGraphPin_Deprecated::get_PinType() {
    return (void*)((uintptr_t)this + 0x50);
}
void* _Script_Engine::EdGraphPin_Deprecated::get_Direction() {
    return (void*)((uintptr_t)this + 0x48);
}
_Script_CoreUObject::Object*& _Script_Engine::EdGraphPin_Deprecated::get_DefaultObject() {
    return *(_Script_CoreUObject::Object**)((uintptr_t)this + 0xc8);
}
void* _Script_Engine::EdGraphPin_Deprecated::get_DefaultValue() {
    return (void*)((uintptr_t)this + 0xa8);
}
void* _Script_Engine::EdGraphPin_Deprecated::get_DefaultTextValue() {
    return (void*)((uintptr_t)this + 0xd0);
}
void* _Script_Engine::EdGraphPin_Deprecated::get_LinkedTo() {
    return (void*)((uintptr_t)this + 0xe8);
}
void* _Script_Engine::EdGraphPin_Deprecated::get_SubPins() {
    return (void*)((uintptr_t)this + 0xf8);
}
_Script_Engine::EdGraphPin_Deprecated*& _Script_Engine::EdGraphPin_Deprecated::get_ReferencePassThroughConnection() {
    return *(_Script_Engine::EdGraphPin_Deprecated**)((uintptr_t)this + 0x110);
}
_Script_Engine::EdGraphPin_Deprecated*& _Script_Engine::EdGraphPin_Deprecated::get_ParentPin() {
    return *(_Script_Engine::EdGraphPin_Deprecated**)((uintptr_t)this + 0x108);
}
_Script_CoreUObject::Class* _Script_Engine::EdGraphPin_Deprecated::static_class() {
    static auto result = (_Script_CoreUObject::Class*)FUObjectArray::get()->find_uobject(L"Class /Script/Engine.EdGraphPin_Deprecated");
    return result;
}
