#pragma once
#include <Windows.h>
#include <cstdint>
#include <string>
#include <string_view>
#include "..\_Script_CoreUObject\Object.hpp"
namespace _Script_CoreUObject {
struct Class;
}
namespace _Script_Engine {
#pragma pack(push, 1)
struct EdGraphPin_Deprecated : public _Script_CoreUObject::Object {
    private: char pad_28[0xf0]; public:
    void* get_PinName();
    void* get_PinToolTip();
    void* get_Direction();
    void* get_PinType();
    void* get_DefaultValue();
    void* get_AutogeneratedDefaultValue();
    _Script_CoreUObject::Object*& get_DefaultObject();
    void* get_DefaultTextValue();
    void* get_LinkedTo();
    void* get_SubPins();
    _Script_Engine::EdGraphPin_Deprecated*& get_ParentPin();
    _Script_Engine::EdGraphPin_Deprecated*& get_ReferencePassThroughConnection();
    static _Script_CoreUObject::Class* static_class();
}; // Size: 0x118
#pragma pack(pop)
}
